### ISSUE TITLE
OS compatibility (remark in README)

### ISSUE THREAD

**Issue by phoeinx** [capellil/iPregel#1]
Hi :) 

I just spent some time trying to compile iPregel under MacOS and was able to fix some issues until I reached the following compile error:
![image](https://user-images.githubusercontent.com/34538290/118963498-c8b46380-b966-11eb-9a07-af85ec00ef6e.png)

As `cpu_set_t` is a Linux-only provided data structure (https://man7.org/linux/man-pages/man3/CPU_SET.3.html), I assume that OS compatibility with macOS (and probably Windows) is just not given and would only be reachable with code modifications.

If I am wrong in my assessment and there actually is a way to compile and run iPregel on macOS, I would be glad and thankful to hear it. Otherwise, only supporting Linux is, of course, totally fine, but maybe adding a remark to the README about OS compatibility could save people some time in the future.

**Comment by capellil** [comment]
Good morning,

Indeed, the XTHI utility used in iPregel relies on cpuset_to_cstr, which is Linux-only. That part of the code was added recently, in commit dc90f417dc46f08518b104428a8fcbd49b0c9d26, to report the placement of OpenMP threads and make sure they reside where you expect them to.

However, this is only for the XTHI utility, the actual source code of iPregel does not have that Linux-only limitation. Feel free to comment out the part of the source code related to the use of XTHI (thanks to the commit mentioned above, you know exactly which parts you can comment out). Just in case, you have 4 lines to remove (or comment out):

1. In src/iPregel_postamble.h:
    1.1 Remove the function call "report_placement();"
    1.2 Remove the header inclusion "xthi.h"
2. In makefile
    2.1 Remove '-D_GNU_SOURCE' from the 'DEFINES' variable
    2.2 Remove '$(SRC_DIRECTORY)/xthi.h' from the 'COMMON_FILES' variable

Nonetheless, indicating that point in the README or disabling this utility on non-linux builds would be a solution.

Hope it helps :)
